### ISSUE TITLE
run without kinect

### ISSUE THREAD

**Issue by lvj5077** [iaslab-unipd/rgbd_calibration#8]
Hi, I am working with your calibration on intel realsense camera. I am wondering if the program work independently with collected data. Also, is there a more detailed install/run instruction to follow?

**Comment by lvj5077** [comment]
In file included from /home/jin/catkin_ws/src/rgbd_calibration/src/rgbd_calibration/checkerboard_views.cpp:21:0:
/home/jin/catkin_ws/src/rgbd_calibration/include/rgbd_calibration/checkerboard_views.h:24:59: fatal error: calibration_common/algorithms/plane_extractor.h: No such file or directory
 #include <calibration_common/algorithms/plane_extractor.h>

**Comment by swtyree** [comment]
Hi @lvj5077, were you able to get this method to work with the RealSense?

**Comment by tiexuedanxin** [comment]
> Hi @lvj5077, were you able to get this method to work with the RealSense?

hello, have you solved the problem.
